name: Auto Hash

on:
  push:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running update.php hash
      run: php update.php hash
    - name: Commit hash.txt
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Update hash.txt
        branch: master
        file_pattern: hash.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
